// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/controller.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JobRequest struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Args                 string   `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobRequest) Reset()         { *m = JobRequest{} }
func (m *JobRequest) String() string { return proto.CompactTextString(m) }
func (*JobRequest) ProtoMessage()    {}
func (*JobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8f4e52e42c22790, []int{0}
}

func (m *JobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobRequest.Unmarshal(m, b)
}
func (m *JobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobRequest.Marshal(b, m, deterministic)
}
func (m *JobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobRequest.Merge(m, src)
}
func (m *JobRequest) XXX_Size() int {
	return xxx_messageInfo_JobRequest.Size(m)
}
func (m *JobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobRequest proto.InternalMessageInfo

func (m *JobRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *JobRequest) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type JobReply struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Args                 string   `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobReply) Reset()         { *m = JobReply{} }
func (m *JobReply) String() string { return proto.CompactTextString(m) }
func (*JobReply) ProtoMessage()    {}
func (*JobReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8f4e52e42c22790, []int{1}
}

func (m *JobReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobReply.Unmarshal(m, b)
}
func (m *JobReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobReply.Marshal(b, m, deterministic)
}
func (m *JobReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobReply.Merge(m, src)
}
func (m *JobReply) XXX_Size() int {
	return xxx_messageInfo_JobReply.Size(m)
}
func (m *JobReply) XXX_DiscardUnknown() {
	xxx_messageInfo_JobReply.DiscardUnknown(m)
}

var xxx_messageInfo_JobReply proto.InternalMessageInfo

func (m *JobReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *JobReply) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func init() {
	proto.RegisterType((*JobRequest)(nil), "proto.JobRequest")
	proto.RegisterType((*JobReply)(nil), "proto.JobReply")
}

func init() {
	proto.RegisterFile("proto/controller.proto", fileDescriptor_c8f4e52e42c22790)
}

var fileDescriptor_c8f4e52e42c22790 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xce, 0xcf, 0x2b, 0x29, 0xca, 0xcf, 0xc9, 0x49, 0x2d, 0xd2, 0x03, 0x0b, 0x08,
	0xb1, 0x82, 0x29, 0x25, 0x23, 0x2e, 0x2e, 0xaf, 0xfc, 0xa4, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2,
	0x12, 0x21, 0x01, 0x2e, 0xe6, 0xdc, 0xe2, 0x74, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x10,
	0x53, 0x48, 0x88, 0x8b, 0x25, 0xb1, 0x28, 0xbd, 0x58, 0x82, 0x09, 0x2c, 0x04, 0x66, 0x2b, 0x19,
	0x70, 0x71, 0x80, 0xf5, 0x14, 0xe4, 0x54, 0x12, 0xa7, 0xc3, 0xc8, 0x9e, 0x8b, 0xcb, 0x19, 0xee,
	0x00, 0x21, 0x43, 0x2e, 0x4e, 0xe7, 0xa2, 0xd4, 0xc4, 0x92, 0x54, 0xaf, 0xfc, 0x24, 0x21, 0x41,
	0x88, 0x7b, 0xf4, 0x10, 0xae, 0x90, 0xe2, 0x47, 0x16, 0x2a, 0xc8, 0xa9, 0x54, 0x62, 0x70, 0x92,
	0xe7, 0x12, 0xce, 0xcc, 0xd7, 0x4b, 0x2f, 0x2a, 0x48, 0xd6, 0x4b, 0x4f, 0xc9, 0x2c, 0xd0, 0x2b,
	0xcf, 0x2f, 0xca, 0x4e, 0x2d, 0x72, 0x62, 0x83, 0xd0, 0x01, 0x8c, 0x49, 0x6c, 0x60, 0x2d, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xde, 0xe3, 0xe2, 0x1b, 0xef, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControllerClient interface {
	CreateJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobReply, error)
}

type controllerClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerClient(cc grpc.ClientConnInterface) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) CreateJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobReply, error) {
	out := new(JobReply)
	err := c.cc.Invoke(ctx, "/proto.Controller/CreateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
type ControllerServer interface {
	CreateJob(context.Context, *JobRequest) (*JobReply, error)
}

// UnimplementedControllerServer can be embedded to have forward compatible implementations.
type UnimplementedControllerServer struct {
}

func (*UnimplementedControllerServer) CreateJob(ctx context.Context, req *JobRequest) (*JobReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJob not implemented")
}

func RegisterControllerServer(s *grpc.Server, srv ControllerServer) {
	s.RegisterService(&_Controller_serviceDesc, srv)
}

func _Controller_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Controller/CreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).CreateJob(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Controller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJob",
			Handler:    _Controller_CreateJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/controller.proto",
}
